// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlaybackStatus } from "./PlaybackStatus";

export type ActiveCue = { cue_id: string, position: number, duration: number, status: PlaybackStatus, };
