[tools]
node = "24"
pnpm = "11"
rust = "stable"
"cargo:tauri-cli" = { version = "2", depends = ["rust"] }
"cargo:cargo-about" = { version = "0.9", depends = ["rust"] }
"cargo:cargo-edit" = { version = "0.13", depends = ["rust"] }
cocogitto = "7"

[tasks.generate_notices]
run = [
'cargo about generate about.hbs --workspace -o THIRD_PARTY_NOTICES.md',
'cd ./sbsp_frontend && pnpm exec license-checker-rseidelsohn --excludePackages sbsp_frontend --direct false --production --json --out ../scripts/tmp.json',
'cd ./scripts && node notice_json2md.js',
'rm ./scripts/tmp.json',
]

[settings]
cargo.binstall_quickinstall = true
