[package]
name = "sbsp_backend"
version = "1.7.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[[bin]]
name = "server"
path = "src/main.rs"
required-features = ["backend", "server", "cli"]

[features]
default = ["backend"]
backend = [
    "dep:tokio",
    "dep:serde_json",
    "dep:rodio",
    "dep:rtrb",
    "dep:symphonia",
    "dep:log",
    "dep:anyhow",
    "dep:ebur128",
    "dep:normpath",
    "dep:sha2",
]
server = [
    "backend",
    "dep:axum",
    "dep:rand",
    "dep:base64",
    "dep:bitflags",
    "dep:mdns-sd",
    "dep:gethostname",
    "dep:serde_json",
]
client = [
    "backend",
    "dep:tokio-tungstenite",
    "dep:futures-util",
    "dep:rand",
    "dep:base64",
    "dep:bitflags",
    "dep:mdns-sd",
    "dep:gethostname",
    "dep:serde_json",
]
cli = ["dep:env_logger", "dep:clap", "dep:termtree"]
type_export = ["dep:ts-rs"]

[dependencies]
serde = { workspace = true, features = ["derive"] }
uuid = { workspace = true, features = ["serde", "v4"] }
indexmap = { version = "2", features = ["serde"] }
log = { workspace = true, optional = true }
tokio = { workspace = true, features = ["rt", "rt-multi-thread", "time", "macros", "sync", "fs", "signal"], optional = true }
serde_json = { workspace = true, optional = true }
rodio = { version = "0.22", default-features = false, features = ["playback", "symphonia-all", "symphonia-simd"], optional = true }
rtrb = { version = "0.3", optional = true }
symphonia = { version = "0.5", features = ["all", "opt-simd"], optional = true }
anyhow = { version = "1.0", optional = true }
ebur128 = { version = "0.1", optional = true }
normpath = { version = "1.5", optional = true }
sha2 = { version = "0.10", optional = true }

env_logger = { version = "0.11", optional = true }
clap = { workspace = true, optional = true }
termtree = { version = "1.0.0", optional = true }

rand = { version = "0.10", optional = true }
base64 = { workspace = true, optional = true }
bitflags = { version = "2.11", optional = true }
mdns-sd = { version = "0.17", optional = true, default-features = false, features = ["async"]}
gethostname = { version = "1.1", optional = true }

axum = { version = "0.8", default-features = false, features = ["tokio", "http1", "http2", "ws"], optional = true }

tokio-tungstenite = { version = "*", optional = true }
futures-util = { version = "0.3", default-features = false, features = ["sink"], optional = true }

ts-rs = { workspace = true, features = ["uuid-impl", "indexmap-impl"], optional = true }

[dev-dependencies]
tempfile = "3.22.0"
env_logger = "0.11"
