// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PermissionInfo } from "./PermissionInfo";

export type ApiServerOptions = { port: number, discoverry: string | null, authMap: Array<PermissionInfo>, };
