// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DarkMode } from "./DarkMode";

export type AppearanceSettings = { language: string | null, darkMode: DarkMode, hideControls: boolean, };
