// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AssetData = { path: string, duration: number | null, waveform: Array<number>, integratedLufs: number | null, peak: number, startTime: number | null, endTime: number | null, };
