// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AssetMetadata = { path: string, duration: number | null, channelCount: number | null, sampleRate: number, };
