// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssetMetadata } from "./AssetMetadata";

export type AssetData = { metadata: AssetMetadata, waveform: Array<number>, integratedLufs: number | null, peak: number, startTime: number | null, endTime: number | null, };
