// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AudioHardwareSettings = { deviceId: string | null, channelCount: number | null, sampleRate: number | null, bufferSize: number | null, };
