// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FadeParam } from "./FadeParam";
import type { SoundType } from "./SoundType";

export type AudioCueParam = { target: string, startTime: number | null, fadeInParam: FadeParam | null, endTime: number | null, fadeOutParam: FadeParam | null, volume: number, pan: number, repeat: boolean, soundType: SoundType, };
