// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BackendError = { "type": "saveToFile", path: string, message: string, } | { "type": "loadFromFile", path: string, message: string, } | { "type": "exportToFolder", path: string, message: string, } | { "type": "cueEdit", message: string, } | { "type": "custom", id: number, message: string, };
