// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CueAction } from "./CueAction";

export type ControllerCommand = { "command": "go" } | { "command": "load", "params": string } | { "command": "pause", "params": string } | { "command": "resume", "params": string } | { "command": "stop", "params": string } | { "command": "seekTo", "params": [string, number] } | { "command": "seekBy", "params": [string, number] } | { "command": "pauseAll" } | { "command": "resumeAll" } | { "command": "stopAll" } | { "command": "performAction", "params": [string, CueAction] } | { "command": "setPlaybackCursor", "params": { cueId: string | null, } };
