// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CueChain } from "./CueChain";
import type { CueParam } from "./CueParam";

export type Cue = { id: string, number: string, name: string | null, notes: string, preWait: number, chain: CueChain, params: CueParam, };
