// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CueChain = { "type": "doNotChain" } | { "type": "afterStart", targetId: string | null, } | { "type": "afterComplete", targetId: string | null, };
