// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudioCueParam } from "./AudioCueParam";
import type { FadeCueParam } from "./FadeCueParam";
import type { GroupMode } from "./GroupMode";
import type { LoadCueParam } from "./LoadCueParam";
import type { PauseCueParam } from "./PauseCueParam";
import type { StartCueParam } from "./StartCueParam";
import type { StopCueParam } from "./StopCueParam";
import type { WaitCueParam } from "./WaitCueParam";

export type CueParam = { "type": "audio" } & AudioCueParam | { "type": "wait" } & WaitCueParam | { "type": "fade" } & FadeCueParam | { "type": "start" } & StartCueParam | { "type": "stop" } & StopCueParam | { "type": "pause" } & PauseCueParam | { "type": "load" } & LoadCueParam | { "type": "group", children: Array<string>, mode: GroupMode, };
