// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudioCueParam } from "./AudioCueParam";
import type { FadeParam } from "./FadeParam";

export type CueParam = { "type": "audio" } & AudioCueParam | { "type": "wait", duration: number, } | { "type": "fade", target: string, volume: number, fadeParam: FadeParam, };
