// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FrameConfig } from "./FrameConfig";

export type DeviceInformation = { name: string, supportedConfigs: Array<FrameConfig>, defaultChannelCount: number, defaultSampleRate: number, };
