// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DownloadEvent = { "event": "started", "data": { contentLength: bigint | null, } } | { "event": "progress", "data": { chunkLength: number, } } | { "event": "finished" };
