// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EditHotkey = { delete: string | null, selectAll: string | null, renumberCues: string | null, cuelistMoveUp: string | null, cuelistExtendUp: string | null, cuelistMoveDown: string | null, cuelistExtendDown: string | null, };
