// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Decibels } from "./Decibels";
import type { FadeParam } from "./FadeParam";

export type FadeCueParam = { target: string, volume: Decibels, fadeParam: FadeParam, };
