// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FileList = { "type": "dir", name: string, files: Array<FileList>, } | { "type": "file", name: string, path: string, extension: string, };
