// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FrameConfig = { channelCount: number, sampleRates: { [key in number]: Array<number> }, };
