// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CursorAdvanceTrigger } from "./CursorAdvanceTrigger";

export type GeneralSettings = { cursorAdvanceTrigger: CursorAdvanceTrigger, lockCursorToSelection: boolean, copyAssetsWhenAdd: boolean, seekAmount: number, };
