// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppearanceSettings } from "./AppearanceSettings";
import type { GeneralSettings } from "./GeneralSettings";
import type { HotkeySettings } from "./HotkeySettings";
import type { TemplateSettings } from "./TemplateSettings";

export type GlobalSettings = { general: GeneralSettings, appearance: AppearanceSettings, hotkey: HotkeySettings, template: TemplateSettings, };
