// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Cue } from "./Cue";
import type { InsertPosition } from "./InsertPosition";
import type { ShowSettings } from "./ShowSettings";

export type ModelCommand = { "command": "updateCue", "params": Cue } | { "command": "addCue", "params": { cue: Cue, position: InsertPosition, } } | { "command": "addCues", "params": { cues: Array<Cue>, position: InsertPosition, } } | { "command": "removeCue", "params": { cueId: string, } } | { "command": "moveCue", "params": { cueId: string, position: InsertPosition, } } | { "command": "renumberCues", "params": { cues: Array<string>, startFrom: number, increment: number, } } | { "command": "updateModelName", "params": string } | { "command": "updateSettings", "params": ShowSettings } | { "command": "reset" } | { "command": "save" } | { "command": "saveToFile", "params": string } | { "command": "exportToFolder", "params": string } | { "command": "loadFromFile", "params": string };
