// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NameFormatSettings = { audio: string, wait: string, fade: string, start: string, stop: string, pause: string, load: string, group: string, };
