// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Permissions } from "./Permissions";

export type PermissionInfo = { password: string, permission: Permissions, };
