// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PlaybackStatus = "loaded" | "preWaiting" | "preWaitPaused" | "playing" | "paused" | "stopping" | "stopped" | "completed" | "error";
