// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PlaybackHotkey = { go: string | null, load: string | null, pauseAndResume: string | null, pauseAll: string | null, resumeAll: string | null, stop: string | null, stopAll: string | null, };
