// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectType } from "./ProjectType";

export type ProjectStatus = { "status": "unsaved" } | { "status": "saved", projectType: ProjectType, path: string, };
