// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShowAudioSettings } from "./ShowAudioSettings";
import type { ShowGeneralSettings } from "./ShowGeneralSettings";
import type { ShowRemoteSettings } from "./ShowRemoteSettings";

export type ShowSettings = { general: ShowGeneralSettings, audio: ShowAudioSettings, remote: ShowRemoteSettings, };
