// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActiveCue } from "./ActiveCue";

export type ShowState = { activeCues: { [key in string]: ActiveCue }, };
