// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudioSettings } from "./AudioSettings";
import type { GeneralSettings } from "./GeneralSettings";
import type { HotkeySettings } from "./HotkeySettings";
import type { TemplateSettings } from "./TemplateSettings";

export type ShowSettings = { general: GeneralSettings, hotkey: HotkeySettings, template: TemplateSettings, audio: AudioSettings, };
