// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeviceInformation } from "./DeviceInformation";

export type SupportedHardware = { default: string, devices: { [key in string]?: DeviceInformation }, };
