// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CueState } from "./CueState";

export type SyncData = { latency: number, cues: Array<CueState>, };
