// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssetData } from "./AssetData";
import type { Cue } from "./Cue";
import type { CueStatusEventParam } from "./CueStatusEventParam";
import type { ProjectType } from "./ProjectType";
import type { ShowModel } from "./ShowModel";
import type { ShowSettings } from "./ShowSettings";
import type { SyncData } from "./SyncData";
import type { UiError } from "./UiError";

export type UiEvent = { "type": "cueStatus", "param": CueStatusEventParam } | { "type": "playbackCursorMoved", "param": { cueId: string | null, } } | { "type": "syncState", "param": SyncData } | { "type": "showModelLoaded", "param": { model: ShowModel, projectType: ProjectType, path: string, } } | { "type": "showModelSaved", "param": { projectType: ProjectType, path: string, } } | { "type": "showModelReset", "param": { model: ShowModel, } } | { "type": "cueRemoved", "param": { cueId: string, } } | { "type": "cueListUpdated", "param": { cues: Array<Cue>, } } | { "type": "settingsUpdated", "param": { newSettings: ShowSettings, } } | { "type": "modelNameUpdated", "param": { newName: string, } } | { "type": "assetResult", "param": { path: string, data: { Ok : AssetData } | { Err : string }, } } | { "type": "operationFailed", "param": { error: UiError, } };
