// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssetProcessorCommand } from "./AssetProcessorCommand";
import type { ControllerCommand } from "./ControllerCommand";
import type { ModelCommand } from "./ModelCommand";

export type WsCommand = { "type": "authenticate", response: string | null, } | { "type": "controll" } & ControllerCommand | { "type": "model" } & ModelCommand | { "type": "assetProcessor" } & AssetProcessorCommand | { "type": "requestAssetList" } | { "type": "requestFullShowState" };
