// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuthInfo } from "./AuthInfo";
import type { BackendEvent } from "./BackendEvent";
import type { FileList } from "./FileList";
import type { FullShowState } from "./FullShowState";

export type WsFeedback = { "type": "hello", "data": { auth: AuthInfo | null, } } | { "type": "authenticated" } | { "type": "event", "data": BackendEvent } | { "type": "assetList", "data": Array<FileList> } | { "type": "fullShowState", "data": FullShowState };
