// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileList } from "./FileList";
import type { FullShowState } from "./FullShowState";
import type { ShowState } from "./ShowState";
import type { UiEvent } from "./UiEvent";

export type WsFeedback = { "type": "event", "data": UiEvent } | { "type": "state", "data": ShowState } | { "type": "assetList", "data": Array<FileList> } | { "type": "fullShowState", "data": FullShowState };
