// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Easing = "Linear" | { "InPowi": number } | { "OutPowi": number } | { "InOutPowi": number } | { "InPowf": number } | { "OutPowf": number } | { "InOutPowf": number };
