// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudioFadeParam } from "./AudioFadeParam";
import type { SoundType } from "./SoundType";

export type AudioCueParam = { target: string, startTime: number | null, fadeInParam: AudioFadeParam | null, endTime: number | null, fadeOutParam: AudioFadeParam | null, volume: number, pan: number, repeat: boolean, soundType: SoundType, };
