// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Easing } from "./Easing";

export type AudioFadeParam = { duration: number, easing: Easing, };
