// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CueParam } from "./CueParam";
import type { CueSequence } from "./CueSequence";

export type Cue = { id: string, number: string, name: string, notes: string, preWait: number, sequence: CueSequence, params: CueParam, };
