// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudioCueFadeParam } from "./AudioCueFadeParam";
import type { AudioCueLevels } from "./AudioCueLevels";
import type { LoopRegion } from "./LoopRegion";

export type CueParam = { "type": "audio", target: string, startTime: number | null, fadeInParam: AudioCueFadeParam | null, endTime: number | null, fadeOutParam: AudioCueFadeParam | null, levels: AudioCueLevels, loopRegion: LoopRegion | null, } | { "type": "wait", duration: number, };
