// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudioCueParam } from "./AudioCueParam";

export type CueParam = { "type": "audio" } & AudioCueParam | { "type": "wait", duration: number, };
