// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudioCueFadeParam } from "./AudioCueFadeParam";

export type CueParam = { "type": "audio", target: string, startTime: number | null, fadeInParam: AudioCueFadeParam | null, endTime: number | null, fadeOutParam: AudioCueFadeParam | null, volume: number, pan: number, repeat: boolean, } | { "type": "wait", duration: number, };
