// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CueSequence = { type: 'doNotContinue' } | { type: 'autoFollow'; targetId: string | null; postWait: number };
