// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CueSequence = "doNotContinue" | { "autoFollow": { target_id: string | null, post_wait: number, } };
