// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Cue } from "./Cue";
import type { ShowSettings } from "./ShowSettings";

export type ShowModel = { name: string, cues: Array<Cue>, settings: ShowSettings, };
