// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudioStateParam } from "./AudioStateParam";

export type StateParam = { "type": "none" } | { "type": "audio" } & AudioStateParam | { "type": "wait" };
