// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Cue } from './Cue';

export type TemplateSettings = { audio: Cue | null; wait: Cue | null };
