name: 'check-license-notices'

on:
  pull_request:
    branches: [dev]
    paths:
      - 'Cargo.lock'
      - 'THIRD_PARTY_NOTICES.md'
      - 'pnpm-lock.yaml'
      - 'about.hbs'
      - 'about.toml'
      - 'scripts/notice_json2md.js'
      - .github/workflows/check-license-notices.yml
  workflow_dispatch:

jobs:
  generate:
    permissions:
      contents: read
    env:
      MISE_ENV: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false

      - uses: cargo-bins/cargo-binstall@main
      - uses: jdx/mise-action@v4

      - name: Get pnpm store path
        id: pnpm-cache
        run: echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: install frontend dependencies
        run: pnpm install --frozen-lockfile # change this to npm, pnpm or bun depending on which one you use.

      - name: Generate notices
        run: |
          mise generate_notices

      - name: Verify no changes
        run: |
          if ! git diff --exit-code THIRD_PARTY_NOTICES.md; then
            echo "::error::THIRD_PARTY_NOTICES.md is not latest. please update via mise generate_notices manually."
            exit 1
          fi
