name: Check PR Title

on:
  pull_request:
    branches: [dev]
    types:
      - opened
      - reopened
      - edited
      # - synchronize (if you use required Actions)

jobs:
  check-title:
    runs-on: ubuntu-slim
    permissions:
      pull-requests: read
    steps:
      - name: Check Conventional Commits format
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          scopes: |
            app
            remote_app
            backend
            frontend
            license
            docs
            deps
