name: 'check-license-notices'

on:
  pull_request:
    branches: [dev]
    paths:
      - 'Cargo.lock'
      - 'THIRD_PARTY_NOTICES.md'
      - 'sbsp_frontend/pnpm-lock.yaml'
      - 'about.hbs'
      - 'about.toml'
      - 'scripts/notice_json2md.js'
      - .github/workflows/check-license-notices.yml
  workflow_dispatch:

jobs:
  generate:
    permissions:
      contents: read

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: setup pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 11

      - name: setup node
        uses: actions/setup-node@v6
        with:
          node-version: lts/*
          cache: pnpm
          cache-dependency-path: sbsp_frontend/pnpm-lock.yaml

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - uses: cargo-bins/cargo-binstall@main

      - run: cargo binstall cargo-about --no-confirm --force

      - name: install dependencies (ubuntu only)
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: install frontend dependencies
        run: pnpm install # change this to npm, pnpm or bun depending on which one you use.
        working-directory: ./sbsp_frontend

      - name: Generate Rust notices
        run: cargo about generate about.hbs --workspace -o THIRD_PARTY_NOTICES.md
        working-directory: ./

      - name: Generate JS notices
        run: pnpm exec license-checker-rseidelsohn --excludePackages sbsp_frontend --direct false --production --json --out ../scripts/tmp.json
        working-directory: ./sbsp_frontend

      - name: Combine notices
        run: |
          node notice_json2md.js
          rm ./tmp.json
        working-directory: ./scripts

      - name: Verify no changes
        run: |
          if ! git diff --exit-code THIRD_PARTY_NOTICES.md; then
            echo "::error::THIRD_PARTY_NOTICES.md is not latest. please update via mise generate_notices manually."
            exit 1
          fi